### ISSUE TITLE
OOCSS with BEM

### ISSUE THREAD

**Issue by HoBi** [kneath/kss#112]
Hi, is it works with BEM syntax - can you add some examples? :)

The BEM uses modifiers (--) and children (__) for object, so how to write documentation? :)

**Comment by janiv** [comment]
Yes, it works fine with BEM. Here's a styleguide using KSS with BEM:

http://scan.me/styleguide/statuses

**Comment by hobi** [comment]
@janiv thanks! 

KSS looks really awesome, I have to try it. :)
