### ISSUE TITLE
Example of KSS?

### ISSUE THREAD

**Issue by ghost** [kneath/kss#123]
Github have changed their styleguide, so the following at (http://warpspire.com/kss/styleguides/) is a 404:
It’s sometimes hard to explain what a living styleguide is. The best way to explain is through examples. The GitHub CSS Styleguide is a good example of a living styleguide generated with KSS. In particular, you can see the value of KSS on pages like the buttons section.

Is there another great example of a KSS styleguide that you can recommend?

**Comment by shoshi** [comment]
@gusseting I can recommend both of these example lists: http://styleguides.io/examples.html, http://saijogeorge.com/brand-style-guide-examples/

Only some are living styleguides and some don't use KSS, but there's usually enough variety in the examples that you can find ones relevant to your current use case.

Github's styleguide has moved to here: http://primercss.io/scaffolding/
